spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/zerobase
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create-drop
